"""Add amount_tendered and change_due to SalesInvoice

Revision ID: 07866954c4c8
Revises: a9c36387bcc7
Create Date: 2026-07-16 09:59:01.408114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07866954c4c8'
down_revision: Union[str, Sequence[str], None] = 'a9c36387bcc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_invoices', sa.Column('amount_tendered', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales_invoices', sa.Column('change_due', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_invoices', 'change_due')
    op.drop_column('sales_invoices', 'amount_tendered')
    # ### end Alembic commands ###
