"""grocery_schema_update

Revision ID: ab5f43793cb1
Revises: 63adf24053f2
Create Date: 2026-07-08 12:07:04.833576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab5f43793cb1'
down_revision: Union[str, Sequence[str], None] = '63adf24053f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['unit_id'], unique=False)
    op.create_table('categories',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['unit_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['unit_id'], unique=False)
    op.create_table('units',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_units_id'), 'units', ['unit_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['unit_id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_purchase_invoices_id'), 'purchase_invoices', ['unit_id'], unique=False)
    op.create_table('sales_invoices',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_sales_invoices_id'), 'sales_invoices', ['unit_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_receipt_number'), 'sales_invoices', ['receipt_number'], unique=True)
    op.create_table('product_batches',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retail_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_product_batches_batch_number'), 'product_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_product_batches_expiry_date'), 'product_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_product_batches_id'), 'product_batches', ['unit_id'], unique=False)
    op.create_table('sales_items',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_applied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.unit_id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.unit_id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_index(op.f('ix_sales_items_id'), 'sales_items', ['unit_id'], unique=False)
    op.add_column('products', sa.Column('barcode', sa.String(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('unit_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('min_stock_alert', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['unit_id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['unit_id'])
    op.create_foreign_key(None, 'products', 'units', ['unit_id'], ['unit_id'])
    op.drop_column('products', 'min_threshold')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'retail_price')
    op.add_column('stock_transactions', sa.Column('warehouse_id', sa.Integer(), nullable=False))
    op.add_column('stock_transactions', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.add_column('stock_transactions', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('stock_transactions', sa.Column('reference_id', sa.String(), nullable=True))
    op.add_column('stock_transactions', sa.Column('notes', sa.String(), nullable=True))
    op.drop_constraint(op.f('stock_transactions_product_id_fkey'), 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transactions', 'product_batches', ['batch_id'], ['unit_id'])
    op.create_foreign_key(None, 'stock_transactions', 'warehouses', ['warehouse_id'], ['unit_id'])
    op.drop_column('stock_transactions', 'type')
    op.drop_column('stock_transactions', 'product_id')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.add_column('stock_transactions', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('stock_transactions', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('stock_transactions_product_id_fkey'), 'stock_transactions', 'products', ['product_id'], ['unit_id'])
    op.drop_column('stock_transactions', 'notes')
    op.drop_column('stock_transactions', 'reference_id')
    op.drop_column('stock_transactions', 'transaction_type')
    op.drop_column('stock_transactions', 'batch_id')
    op.drop_column('stock_transactions', 'warehouse_id')
    op.add_column('products', sa.Column('retail_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('cost_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('min_threshold', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_column('products', 'min_stock_alert')
    op.drop_column('products', 'tax_rate')
    op.drop_column('products', 'unit_id')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'barcode')
    op.drop_index(op.f('ix_sales_items_id'), table_name='sales_items')
    op.drop_table('sales_items')
    op.drop_index(op.f('ix_product_batches_id'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_expiry_date'), table_name='product_batches')
    op.drop_index(op.f('ix_product_batches_batch_number'), table_name='product_batches')
    op.drop_table('product_batches')
    op.drop_index(op.f('ix_sales_invoices_receipt_number'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_id'), table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index(op.f('ix_purchase_invoices_id'), table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
