"""initial_models

Revision ID: b13e96f04310
Revises: ab5f43793cb1
Create Date: 2026-07-10 16:39:35.027875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13e96f04310'
down_revision: Union[str, Sequence[str], None] = 'ab5f43793cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_batch', 'product_batches', ['product_id', 'batch_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_batch', 'product_batches', type_='unique')
    # ### end Alembic commands ###
